
# Install Cask
brew install brew-cask


# Install dev things
brew install eck
brew install go
brew install node

# Install Apps
brew cask install google-chrome
brew cask install alfred
brew cask install iterm2
brew cask install visual-studio-code
brew cask install spotify
brew cask install slack
brew cask install 1password-cli
brew cask install simplenote
